#cloud-config
write_files:
  -   path: /etc/server.conf
      owner: root:root
      permissions: "0644"
      content: |
        {
          "user":  "${user}",
          "password": "${password}",
          "database": "${database}",
          "netloc": "${hostname}:${port}"
        }
runcmd:
  - sudo yum update -y
  - sudo yum install git -y
  - sudo yum install gcc g++ make -y
  - git clone https://github.com/gilles-christian/simple-inventory-app-lab
packages:
  - jq
  - wget
  - unzip
  - node
